name: galaxy-publish

on:
  release:
    types: [published]

jobs:
  publish:
    uses: wittdennis/pipelines/.github/workflows/ansible-galaxy-publish.yaml@bb1063c3cf234c2ffa332404f130ce86259d7e0c # 2.0.3
    secrets:
      galaxy-api-token: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
