name: github-release

on:
  workflow_dispatch:

jobs:
  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@bb1063c3cf234c2ffa332404f130ce86259d7e0c # 2.0.3
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
